name: Build and Test C++ Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Step 3: Pull the Docker container image
      - name: Pull Container Image
        run: docker pull ghcr.io/casparquast/my-container:latest

      # Step 4: Build and Test the C++ Application using the Container
      - name: Build and Test
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/casparquast/my-container:latest /bin/bash -c "
            mkdir -p build &&
            cd build &&
            cmake .. &&
            make &&
            # You can add your testing command here if applicable
            echo 'Build completed successfully'
          "
